version: '3.9'
services:
  master:
    image: chrislusf/seaweedfs
    command: >
      master
      -port=9333
      -mdir=/data/master
    ports:
      - "9333:9333"
    volumes:
      - ./data/master:/data/master

  volume:
    image: chrislusf/seaweedfs
    command: >
      volume
      -mserver=master:9333
      -dir=/data/volume
      -port=8080
    ports:
      - "8080:8080"
    volumes:
      - ./data/volume:/data/volume
    depends_on:
      - master

  filer:
    image: chrislusf/seaweedfs
    command: >
      filer
      -master=master:9333
      -port=8888
    ports:
      - "8888:8888"
    volumes:
      - ./data/filer:/data/filer
    depends_on:
      - master
      - volume
